-- Migration: Agent System Tables
-- Description: Adds tables for multi-agent AI orchestration system
-- Date: 2025-12-16

-- Table 1: Agent Decision Logging
-- Tracks all AI agent executions and decisions for audit and debugging
CREATE TABLE IF NOT EXISTS agent_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    agent_name TEXT NOT NULL,
    input_data TEXT,
    output_data TEXT,
    execution_time_ms INTEGER,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);

-- Table 2: Patient Alerts
-- Stores alerts generated by Vital Trend Analyzer and other monitoring agents
CREATE TABLE IF NOT EXISTS patient_alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    message TEXT NOT NULL,
    vital_name TEXT,
    trend_data TEXT,
    is_acknowledged BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    acknowledged_at DATETIME,
    acknowledged_by TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);

-- Table 3: Follow-up Schedule
-- Automated follow-up scheduling by Follow-up Care Agent
CREATE TABLE IF NOT EXISTS follow_up_schedule (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    scheduled_date DATE NOT NULL,
    visit_type TEXT NOT NULL,
    priority TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING',
    created_by_agent TEXT,
    notes TEXT,
    completed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_agent_logs_patient ON agent_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_agent_logs_timestamp ON agent_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_patient_alerts_patient ON patient_alerts(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_alerts_severity ON patient_alerts(severity, is_acknowledged);
CREATE INDEX IF NOT EXISTS idx_follow_up_schedule_patient ON follow_up_schedule(patient_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_schedule_date ON follow_up_schedule(scheduled_date, status);

-- Insert sample data for testing
-- Sample alert for demonstration
INSERT INTO patient_alerts (patient_id, alert_type, severity, message, vital_name, trend_data, is_acknowledged)
VALUES (1, 'VITAL_TREND_WORSENING', 'HIGH', 'Blood pressure rising trend detected (30 points in 5 days)', 'BP', 
'{"readings": [{"value": "130/85", "date": "2025-12-11"}, {"value": "145/90", "date": "2025-12-13"}, {"value": "160/95", "date": "2025-12-16"}]}', 0);

-- Sample follow-up schedule
INSERT INTO follow_up_schedule (patient_id, scheduled_date, visit_type, priority, created_by_agent, notes)
VALUES (1, DATE('now', '+2 days'), 'BP Monitoring', 'HIGH', 'vital_trend_analyzer', 'Check BP trend and medication adherence');

PRAGMA foreign_keys = ON;
